#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Class-Factory-Util
Version  : 1.7
Release  : 13
URL      : https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Class-Factory-Util-1.7.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Class-Factory-Util-1.7.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libc/libclass-factory-util-perl/libclass-factory-util-perl_1.7-3.debian.tar.xz
Summary  : Provide utility methods for factory classes
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-2.0
Requires: perl-Class-Factory-Util-license = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
NAME
Class::Factory::Util - Provide utility methods for factory classes
SYNOPSIS
package My::Class;

%package dev
Summary: dev components for the perl-Class-Factory-Util package.
Group: Development
Provides: perl-Class-Factory-Util-devel = %{version}-%{release}

%description dev
dev components for the perl-Class-Factory-Util package.


%package license
Summary: license components for the perl-Class-Factory-Util package.
Group: Default

%description license
license components for the perl-Class-Factory-Util package.


%prep
%setup -q -n Class-Factory-Util-1.7
cd ..
%setup -q -T -D -n Class-Factory-Util-1.7 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Class-Factory-Util-1.7/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Class-Factory-Util
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-Class-Factory-Util/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/package-licenses/perl-Class-Factory-Util/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.1/Class/Factory/Util.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Class::Factory::Util.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Class-Factory-Util/LICENSE
/usr/share/package-licenses/perl-Class-Factory-Util/deblicense_copyright
